// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/external_api.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	types "github.com/dhafinmuktafin/omdb-client-api/internal/model/types"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockExternalAPIRepo is a mock of ExternalAPIRepo interface
type MockExternalAPIRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExternalAPIRepoMockRecorder
}

// MockExternalAPIRepoMockRecorder is the mock recorder for MockExternalAPIRepo
type MockExternalAPIRepoMockRecorder struct {
	mock *MockExternalAPIRepo
}

// NewMockExternalAPIRepo creates a new mock instance
func NewMockExternalAPIRepo(ctrl *gomock.Controller) *MockExternalAPIRepo {
	mock := &MockExternalAPIRepo{ctrl: ctrl}
	mock.recorder = &MockExternalAPIRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExternalAPIRepo) EXPECT() *MockExternalAPIRepoMockRecorder {
	return m.recorder
}

// GetMovieListByKeyword mocks base method
func (m *MockExternalAPIRepo) GetMovieListByKeyword(arg0 context.Context, arg1 int64, arg2 string) (types.SearchMovieResult, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovieListByKeyword", arg0, arg1, arg2)
	ret0, _ := ret[0].(types.SearchMovieResult)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMovieListByKeyword indicates an expected call of GetMovieListByKeyword
func (mr *MockExternalAPIRepoMockRecorder) GetMovieListByKeyword(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieListByKeyword", reflect.TypeOf((*MockExternalAPIRepo)(nil).GetMovieListByKeyword), arg0, arg1, arg2)
}

// GetMovieDetails mocks base method
func (m *MockExternalAPIRepo) GetMovieDetails(arg0 context.Context, arg1 string) (types.MovieDetails, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovieDetails", arg0, arg1)
	ret0, _ := ret[0].(types.MovieDetails)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMovieDetails indicates an expected call of GetMovieDetails
func (mr *MockExternalAPIRepoMockRecorder) GetMovieDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovieDetails", reflect.TypeOf((*MockExternalAPIRepo)(nil).GetMovieDetails), arg0, arg1)
}
